[project]
name = "specdec-pp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=2.14.0,<3",
    "huggingface-hub>=0.36.0,<1",
    "numpy<2",
    "pyarrow>=14,<15",
    "scipy>=1.15.0",
    "torch==2.4.1",
    "torchaudio==2.4.1",
    "torchvision==0.19.1",
    "transformers>=4.34.0,<5",
    "vllm==0.6.4.post1",
    "wandb>=0.25.0",
]
